[2022-07-27 15:08:13,997] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag.inaccurate scheduled__2022-07-26T00:00:00+00:00 [queued]>
[2022-07-27 15:08:14,031] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag.inaccurate scheduled__2022-07-26T00:00:00+00:00 [queued]>
[2022-07-27 15:08:14,032] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 15:08:14,032] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-27 15:08:14,039] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-27 15:08:14,088] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): inaccurate> on 2022-07-26 00:00:00+00:00
[2022-07-27 15:08:14,100] {standard_task_runner.py:52} INFO - Started process 1687 to run task
[2022-07-27 15:08:14,113] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag', 'inaccurate', 'scheduled__2022-07-26T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpfv35_rza', '--error-file', '/tmp/tmp7vr2j5so']
[2022-07-27 15:08:14,114] {standard_task_runner.py:80} INFO - Job 65: Subtask inaccurate
[2022-07-27 15:08:14,330] {task_command.py:371} INFO - Running <TaskInstance: dag.inaccurate scheduled__2022-07-26T00:00:00+00:00 [running]> on host c054a673cb8f
[2022-07-27 15:08:14,581] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-26T00:00:00+00:00
[2022-07-27 15:08:14,584] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-27 15:08:14,585] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-07-27 15:08:14,614] {subprocess.py:85} INFO - Output:
[2022-07-27 15:08:14,619] {subprocess.py:92} INFO - inaccurate
[2022-07-27 15:08:14,622] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-27 15:08:14,723] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dag, task_id=inaccurate, execution_date=20220726T000000, start_date=20220727T150813, end_date=20220727T150814
[2022-07-27 15:08:14,778] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-27 15:08:14,856] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
